<?php
/**
 * The homepage template file.
 *
 * @package WordPress
 * @subpackage ChurchThemes
 *
 ===================================================================================================
 WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

 To make it easy to update your theme, you should not edit this file. Instead, you should create a
 Child Theme first. This will ensure your template changes are not lost when updating the theme.

 You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

 You have been warned! :)
 ===================================================================================================
 */

get_header(); ?>
		<div id="wrapper3" class="container_12">
			<div class="grid_4 alpha">
				<?php dynamic_sidebar('Homepage Left'); ?>
			</div>
			<div class="grid_4">
				<?php dynamic_sidebar('Homepage Center'); ?>
			</div>
			<div class="grid_4 omega">
				<?php dynamic_sidebar('Homepage Right'); ?>
			</div>
		</div>
<?php get_footer(); ?>