<?php
/*
===================================================================================================
WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

To make it easy to update your theme, you should not edit this file. Instead, you should create a
Child Theme first. This will ensure your template changes are not lost when updating the theme.

You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

You have been warned! :)
===================================================================================================
*/
?>
<?php

$theme_options = get_option('ct_theme_options');
isset($theme_options['favicon']) ? $ct_favicon = $theme_options['favicon'] : $ct_favicon = null;
isset($theme_options['ios_icon']) ? $ct_ios_icon = $theme_options['ios_icon'] : $ct_ios_icon = null;
isset($theme_options['custom_css']) ? $ct_custom_css = $theme_options['custom_css'] : $ct_custom_css = null;

$slide_settings = get_option('ct_slide_settings');
isset($slide_settings['visibility']) ? $visibility = $slide_settings['visibility'] : $visibility = null;

?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo('charset'); ?>" />
<title><?php wp_title('|', true, 'right'); bloginfo('name'); ?></title>
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
<?php if($ct_favicon): ?>
<link rel="icon" type="image/png" href="<?php echo $ct_favicon; ?>" />
<?php endif; ?>
<?php if($ct_ios_icon): ?>
<link rel="apple-touch-icon" href="<?php echo $ct_ios_icon; ?>" />
<?php endif; ?>
<?php wp_head(); ?>
<?php if($ct_custom_css): ?>
<style type="text/css">
<?php echo $ct_custom_css; ?>
</style>
<?php endif; ?>

</head>
<body <?php body_class('no-js'); ?>>
<div id="wrapper">
	<div id="wrapper2">
		<div id="header" class="container_12">
			<div class="grid_3 alpha logo">
				<a href="<?php echo home_url('/'); ?>" title="<?php echo esc_attr(get_bloginfo('name', 'display')); ?> - <?php echo esc_attr(get_bloginfo('description', 'display')); ?>" rel="home"><?php bloginfo('name'); ?></a>
			</div>
			<div class="grid_9 omega nav">
				<?php ct_primary_nav_menu(); ?>
			</div>
		</div>
<?php if(is_front_page() && $visibility != 'off') get_template_part('slider'); ?>
