<?php
/*
===================================================================================================
WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

To make it easy to update your theme, you should not edit this file. Instead, you should create a
Child Theme first. This will ensure your template changes are not lost when updating the theme.

You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

You have been warned! :)
===================================================================================================
*/
?>
<?php

$person_settings = get_option('ct_person_settings');
isset($person_settings['orderby']) ? $orderby = $person_settings['orderby'] : $orderby = null;
isset($person_settings['order']) ? $order = $person_settings['order'] : $order = null;

if(empty($orderby)) $orderby = 'date';
if(empty($order)) $order = 'DESC';

global $post;

$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;

if($orderby == 'views'):
	$args=array(
		'post_type' => 'ct_person',
		'post_status' => 'publish',
		'paged' => $paged,
		'meta_key' => 'Views',
		'orderby' => 'meta_value_num',
		'order' => $order,
		'person_tag' => get_query_var('person_tag'),
		'person_category' => get_query_var('person_category'),
	);
else:
	$args=array(
		'post_type' => 'ct_person',
		'post_status' => 'publish',
		'paged' => $paged,
		'orderby' => $orderby,
		'order' => $order,
		'person_tag' => get_query_var('person_tag'),
		'person_category' => get_query_var('person_category'),
	);
endif;
		
$query = null;
$query = new WP_Query($args);

$i = 0;

if($query->have_posts()): while($query->have_posts()): $query->the_post();

$i++;

$person_role = get_post_meta($post->ID, '_ct_ppl_role', true);

$img_atts = array(
	'alt'	=> trim(strip_tags($post->post_title)),
	'title'	=> trim(strip_tags($post->post_title)),
);
?>
<div <?php if($i == 1): echo post_class('post ct_person first'); else: post_class('post ct_person'); endif; ?>>
	<h2><a href="<?php the_permalink(); ?>" title="<?php printf(esc_attr__('Permalink to %s', 'churchthemes'), the_title_attribute('echo=0')); ?>" rel="bookmark"><?php the_title(); ?></a></h2>
<?php if($person_role): ?>
	<h4><?php echo $person_role; ?></h4>
<?php endif; ?>
	<div class="excerpt">
		<div class="image"><a href="<?php the_permalink(); ?>" title="<?php the_title_attribute('echo=0'); ?>" rel="bookmark"><?php echo get_the_post_thumbnail($post->ID, 'archive', $img_atts); ?></a></div>
		<p><?php the_excerpt(); ?><p>
		<?php ct_person_contact(); ?>
		<?php ct_person_social(); ?>
	</div>
	<div class="clear"></div>
</div>
<?php endwhile; else: ?>
<div class="post ct_person first">
	<h2><?php _e('No results found', 'churchthemes'); ?></h2>
	<p><?php _e('Sorry, nothing was found matching that criteria.', 'churchthemes'); ?></p>
</div>
<?php endif; ?>
<?php if($query->max_num_pages > 1): pagination($query->max_num_pages); endif; wp_reset_query(); ?>