<?php
/*
===================================================================================================
WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

To make it easy to update your theme, you should not edit this file. Instead, you should create a
Child Theme first. This will ensure your template changes are not lost when updating the theme.

You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

You have been warned! :)
===================================================================================================
*/
?>
<?php

$settings = get_option('ct_social_footer_settings');
$social = isset( $settings['social_footer'] ) ? $settings['social_footer'] : null;

$title = ( $settings['title'] ) ? $settings['title'] : __( 'Connect With Us', 'churchthemes' );
$facebook = $settings['facebook'];
$twitter = $settings['twitter'];
$flickr = $settings['flickr'];
$youtube = $settings['youtube'];
$vimeo = $settings['vimeo'];
?>
<?php if ( ( $social == 'on' || !$social ) && ( $facebook || $twitter || $flickr || $youtube || $vimeo ) ) : ?>
		<div class="container_12">
			<div class="grid_12 alpha social_bar">
				<div class="grid_3 alpha title">
					<h3><?php echo $title; ?></h3>
				</div>
				<div class="grid_9 omega connect">
					<ul>
						<?php if($vimeo): ?><li><a href="<?php echo esc_url( $vimeo ); ?>" class="vimeo"><?php _e( 'Vimeo', 'churchthemes' ); ?></a></li><?php endif; ?>
						<?php if($youtube): ?><li><a href="<?php echo esc_url( $youtube ); ?>" class="youtube"><?php _e( 'YouTube', 'churchthemes' ); ?></a></li><?php endif; ?>
						<?php if($flickr): ?><li><a href="<?php echo esc_url( $flickr ); ?>" class="flickr"><?php _e( 'Flickr', 'churchthemes' ); ?></a></li><?php endif; ?>
						<?php if($twitter): ?><li><a href="<?php echo esc_url( $twitter ); ?>" class="twitter"><?php _e( 'Twitter', 'churchthemes' ); ?></a></li><?php endif; ?>
						<?php if($facebook): ?><li><a href="<?php echo esc_url( $facebook ); ?>" class="facebook"><?php _e( 'Facebook', 'churchthemes' ); ?></a></li><?php endif; ?>
					</ul>
				</div>
			</div>
		</div>
<?php endif; ?>
